//
// Created by Antony Peacock on 11/12/2019.
//

#ifndef LINEAR_ALGEBRA_SIMD_LINEAR_ALGEBRA_SIMD_HPP
#define LINEAR_ALGEBRA_SIMD_LINEAR_ALGEBRA_SIMD_HPP

#endif //LINEAR_ALGEBRA_SIMD_LINEAR_ALGEBRA_SIMD_HPP
